<a href="https://colab.research.google.com/github/Sf99-lab/NumPy/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                 NumPy Basics

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim

2

In [ ]:
a.dtype.name

'int64'

**a.itemsize:**This attribute returns the length of one array element in bytes1. For example, if you have an array of type np.float64, a.itemsize would return 8 because a float64 takes up 8 bytes1. If the array is of type np.complex128, a.itemsize would return 161.

In [ ]:
a.itemsize

8

**a.size:** This attribute gives the total number of elements present in the array2.

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [ ]:
type(b)

numpy.ndarray

**Array Creation**

In [ ]:
import numpy as np
a = np.array([2, 3, 4])
a


array([2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [ ]:
a = np.array(1, 2, 3, 4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
a = np.array([1, 2, 3, 4])  # RIGHT

transform sequences of sequences into two d arrays and so on.

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
#SPECIFY ARRAY TYPE AT CREATION TIME
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

**`zeros` function, `ones` function, and `empty` function**

In [ ]:
np.zeros((3, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
#empty creates an array whose initial content is random and depends on the state of the memory.
np.empty((2, 3))

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

**Create sequences of numbers**

In [ ]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [ ]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

`linspace` **receives as an argument the number of elements that we want, instead of the step:**

In [ ]:
np.linspace(0, 2, 6)                   # 9 numbers from 0 to 2

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [ ]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

**Printing Arrays**

In [ ]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [ ]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [ ]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
import sys
#This will set the threshold for printing NumPy arrays to the maximum possible value,
# allowing the user to see the entire array without truncation.
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

  **Basic Operations**

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [ ]:
c = a - b
c

array([20, 29, 38, 47])

In [ ]:
b**2

array([0, 1, 4, 9])

In [ ]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
a < 35

array([ True,  True, False, False])

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A @ B  # matrix product


array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
b += a
b

array([[6.51182162, 6.9504637 , 6.14415961],
       [6.94864945, 6.31183145, 6.42332645]])

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [ ]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [ ]:
c.dtype.name

'float64'

In [ ]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [ ]:
d.dtype.name

'complex128'

**Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.**

In [ ]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [ ]:
a.sum()

3.1057109529998157

In [ ]:
a.min()

0.027559113243068367

In [ ]:
a.max()

0.8277025938204418

> **by specifying the axis parameter we can apply an operation along the specified axis of an array:**

>



In [ ]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.sum(axis=0)     # sum of each column

array([12, 15, 18, 21])

In [ ]:
b.min(axis=1)     # min of each row

array([0, 4, 8])

In [ ]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Universal functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [1]:
import numpy as np
B = np.arange(3)
B

array([0, 1, 2])

In [ ]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [ ]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

# Indexing, slicing and iterating:

One-dimensional arrays

In [2]:
 a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [3]:
a[6]

216

In [8]:
a[2 : 3]

array([8])

In [9]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000

a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [10]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [11]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


**indexing, slicing, and iterating Multidimensional arrays**

In [12]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [13]:
b[2, 3]

23

In [14]:
b[0:5, 1]  # each row in the second column of b


array([ 1, 11, 21, 31, 41])

In [15]:
b[:, 1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [16]:
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [17]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

x[1, 2, ...] is equivalent to x[1, 2, :, :, :],

x[..., 3] to x[:, :, :, :, 3] and

x[4, ..., 5, :] to x[4, :, :, 5, :].

In [19]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [20]:
c[1, ...]  # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [21]:
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays

In [22]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


 one can use the flat attribute which is an iterator over all the elements of the array. This is useful if one wants to perform an operation on each element in the array

In [23]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
