<a href="https://colab.research.google.com/github/Sf99-lab/NumPy/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#                 NumPy Basics

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim

2

In [ ]:
a.dtype.name

'int64'

**a.itemsize:**This attribute returns the length of one array element in bytes1. For example, if you have an array of type np.float64, a.itemsize would return 8 because a float64 takes up 8 bytes1. If the array is of type np.complex128, a.itemsize would return 161.

In [ ]:
a.itemsize

8

**a.size:** This attribute gives the total number of elements present in the array2.

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [ ]:
type(b)

numpy.ndarray

**Array Creation**

In [1]:
import numpy as np
a = np.array([2, 3, 4])
a


array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [13]:
a = np.array(1, 2, 3, 4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [14]:
a = np.array([1, 2, 3, 4])  # RIGHT

transform sequences of sequences into two d arrays and so on.

In [15]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
#SPECIFY ARRAY TYPE AT CREATION TIME
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

**`zeros` function, `ones` function, and `empty` function**

In [19]:
np.zeros((3, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2, 3, 4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [24]:
#empty creates an array whose initial content is random and depends on the state of the memory.
np.empty((2, 3))

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

**Create sequences of numbers**

In [29]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [30]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

`linspace` **receives as an argument the number of elements that we want, instead of the step:**

In [36]:
from numpy import pi
np.linspace(0, 2, 6)                   # 9 numbers from 0 to 2

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [38]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

**Printing Arrays**

In [39]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [40]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [43]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [47]:
import sys
#This will set the threshold for printing NumPy arrays to the maximum possible value,
# allowing the user to see the entire array without truncation.
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported